# Generated by Django 2.1.1 on 2018-09-10 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theapplication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='status',
            field=models.CharField(choices=[('NS', 'Application Not Started'), ('IP', 'Application In Progress'), ('AD', 'Awaiting Decision'), ('OD', 'Application Not Submitted By Deadline'), ('WA', 'Waitlist'), ('NA', 'Not Admitted'), ('AM', 'Admitted')], default='NS', max_length=2),
        ),
    ]
