# Generated by Django 2.1.2 on 2018-10-26 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("theapplication", "0001_initial")]

    operations = [
        migrations.RemoveField(model_name="application", name="race"),
        migrations.AddField(
            model_name="application",
            name="race",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.DeleteModel(name="RaceSelectMultiple"),
    ]
