# Generated by Django 2.1.2 on 2018-11-01 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theapplication', '0002_auto_20181026_2339'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaceChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race_string', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='application',
            name='code_of_conduct',
        ),
        migrations.RemoveField(
            model_name='application',
            name='inforelease',
        ),
        migrations.RemoveField(
            model_name='application',
            name='is_adult',
        ),
        migrations.RemoveField(
            model_name='application',
            name='termsconditions',
        ),
    ]
