# Generated by Django 2.1.2 on 2018-11-01 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("theapplication", "0003_auto_20181101_1820")]

    operations = [
        migrations.AddField(
            model_name="application",
            name="race_select",
            field=models.ManyToManyField(to="theapplication.RaceChoice"),
        )
    ]
