# Generated by Django 2.1.2 on 2018-12-20 18:46

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [("theapplication", "0014_auto_20181220_1653")]

    operations = [
        migrations.RemoveField(model_name="application", name="resume"),
        migrations.AlterField(
            model_name="application",
            name="gender",
            field=models.CharField(
                choices=[
                    ("M_", "Male"),
                    ("NB", "Nonbinary"),
                    ("F_", "Female"),
                    ("O_", "Other"),
                    ("P_", "Prefer not to answer"),
                ],
                max_length=2,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="grad_year",
            field=models.CharField(
                choices=[
                    ("19", "2019"),
                    ("20", "2020"),
                    ("21", "2021"),
                    ("22", "2022"),
                    ("23", "2023 or later"),
                    ("or", "other"),
                ],
                max_length=2,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, null=True
            ),
        ),
        migrations.AlterField(
            model_name="confirmation",
            name="shirt_size",
            field=models.CharField(
                choices=[
                    ("XS", "XS"),
                    ("S_", "S"),
                    ("M_", "M"),
                    ("L_", "L"),
                    ("1X", "XL"),
                    ("2X", "XXL"),
                ],
                max_length=2,
                null=True,
            ),
        ),
    ]
