# Generated by Django 2.1.2 on 2018-12-20 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theapplication', '0016_auto_20181220_1919'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_string', models.CharField(max_length=200)),
            ],
        ),
    ]
