# Generated by Django 2.1.2 on 2018-12-20 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("theapplication", "0017_schoolchoice")]

    operations = [
        migrations.RemoveField(model_name="application", name="school"),
        migrations.AddField(
            model_name="application",
            name="school",
            field=models.ManyToManyField(
                to="theapplication.SchoolChoice",
                verbose_name="Where do you attend school?",
            ),
        ),
    ]
