# Generated by Django 2.1.2 on 2018-12-21 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("theapplication", "0019_auto_20181221_0627")]

    operations = [
        migrations.AddField(
            model_name="application",
            name="expanding_brain_1",
            field=models.CharField(
                max_length=150, null=True, verbose_name="Expanding Brain 1"
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="expanding_brain_2",
            field=models.CharField(
                max_length=150, null=True, verbose_name="Expanding Brain 2"
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="expanding_brain_3",
            field=models.CharField(
                max_length=150, null=True, verbose_name="Expanding Brain 3"
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="expanding_brain_4",
            field=models.CharField(
                max_length=150, null=True, verbose_name="Expanding Brain 4"
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="is_this_a",
            field=models.CharField(
                max_length=150, null=True, verbose_name="Is this..."
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="pikachu",
            field=models.TextField(max_length=500, null=True, verbose_name="Pikachu"),
        ),
        migrations.AlterField(
            model_name="application",
            name="legal1",
            field=models.BooleanField(default=False, verbose_name=""),
        ),
        migrations.AlterField(
            model_name="application",
            name="legal2",
            field=models.BooleanField(default=False, verbose_name=""),
        ),
        migrations.AlterField(
            model_name="application",
            name="legal3",
            field=models.BooleanField(default=False, verbose_name=""),
        ),
    ]
