# Generated by Django 2.1.2 on 2018-12-21 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("theapplication", "0020_auto_20181221_0706")]

    operations = [migrations.RemoveField(model_name="application", name="essay4")]
