# Generated by Django 2.1.2 on 2018-12-21 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("theapplication", "0021_remove_application_essay4")]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="pikachu",
            field=models.CharField(max_length=500, null=True, verbose_name="Pikachu"),
        )
    ]
