# Generated by Django 2.1.2 on 2018-12-21 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("theapplication", "0022_auto_20181221_0708")]

    operations = [
        migrations.RenameField(
            model_name="application", old_name="expanding_brain_2", new_name="brain_2"
        ),
        migrations.RenameField(
            model_name="application", old_name="expanding_brain_3", new_name="brain_3"
        ),
        migrations.RenameField(
            model_name="application", old_name="expanding_brain_4", new_name="brain_4"
        ),
        migrations.RemoveField(model_name="application", name="expanding_brain_1"),
        migrations.AddField(
            model_name="application",
            name="brain_1",
            field=models.CharField(max_length=150, null=True, verbose_name=""),
        ),
        migrations.AlterField(
            model_name="application",
            name="is_this_a",
            field=models.CharField(max_length=150, null=True, verbose_name=""),
        ),
        migrations.AlterField(
            model_name="application",
            name="pikachu",
            field=models.CharField(max_length=500, null=True, verbose_name=""),
        ),
    ]
