# Generated by Django 2.1.2 on 2018-12-22 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theapplication', '0023_auto_20181221_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='study_level',
            field=models.CharField(choices=[('HS', 'High school or below'), ('1Y', '1st year'), ('2Y', '2nd year'), ('3Y', '3rd year'), ('4Y', '4th year'), ('5Y', '5th year and beyond'), ('GS', 'Graduate Student'), ('GR', 'Graduated/out of school')], max_length=2, null=True, verbose_name='What is your current level of study?'),
        ),
    ]
