# Generated by Django 2.1.2 on 2018-12-22 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("theapplication", "0024_auto_20181222_0250")]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="birth_date",
            field=models.DateField(
                help_text="MM/DD/YYYY - Because of limitations imposed by our venue, we are not legally allowed to host minors (those under 18) for Uncommon Hacks 2019.",
                null=True,
                verbose_name="Birth Date",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="location",
            field=models.CharField(
                help_text="city, province, country",
                max_length=200,
                null=True,
                verbose_name="Where are you coming from to attend Uncommon Hacks?",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="phone_number",
            field=models.CharField(
                help_text="###-###-####",
                max_length=20,
                null=True,
                verbose_name="Phone Number",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="school",
            field=models.ManyToManyField(
                help_text="SELECT OTHER",
                to="theapplication.SchoolChoice",
                verbose_name='Where do you attend school? If your school does not appear on the list, select "Other".',
            ),
        ),
    ]
