# Generated by Django 2.1.2 on 2018-12-23 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theapplication', '0027_auto_20181223_0709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='is_this_a',
        ),
        migrations.AddField(
            model_name='application',
            name='is_this_a_1',
            field=models.CharField(max_length=150, null=True, verbose_name='Who'),
        ),
        migrations.AddField(
            model_name='application',
            name='is_this_a_2',
            field=models.CharField(max_length=150, null=True, verbose_name='Butterfly'),
        ),
        migrations.AddField(
            model_name='application',
            name='is_this_a_3',
            field=models.CharField(max_length=150, null=True, verbose_name='Is this...'),
        ),
    ]
