# Generated by Django 2.1.2 on 2018-12-23 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("theapplication", "0030_auto_20181223_2100")]

    operations = [
        migrations.AlterField(
            model_name="confirmation",
            name="dietary_restrictions",
            field=models.CharField(
                max_length=1000, verbose_name="Do you have any dietary restrictions?"
            ),
        ),
        migrations.AlterField(
            model_name="confirmation",
            name="notes",
            field=models.TextField(
                max_length=1500,
                null=True,
                verbose_name="Anything else we should know? (health information, accommodations, etc.)",
            ),
        ),
        migrations.AlterField(
            model_name="confirmation",
            name="shirt_size",
            field=models.CharField(
                choices=[
                    ("XS", "XS"),
                    ("S_", "S"),
                    ("M_", "M"),
                    ("L_", "L"),
                    ("1X", "XL"),
                    ("2X", "XXL"),
                ],
                max_length=2,
                null=True,
                verbose_name="Shirt Size",
            ),
        ),
    ]
