# Generated by Django 2.1.2 on 2019-01-25 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theapplication', '0033_confirmation_over18'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmation',
            name='wherefrom',
            field=models.TextField(max_length=200, null=True, verbose_name='Where are you coming from? (city, state, etc.)'),
        ),
        migrations.AddField(
            model_name='confirmation',
            name='will_show',
            field=models.BooleanField(default=False, verbose_name=''),
        ),
    ]
