# Generated by Django 2.1.2 on 2019-01-26 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theapplication', '0034_auto_20190125_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirmation',
            name='over18',
        ),
        migrations.RemoveField(
            model_name='confirmation',
            name='will_show',
        ),
    ]
