# Generated by Django 2.1.2 on 2019-01-26 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theapplication', '0035_auto_20190126_0309'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmation',
            name='over18',
            field=models.BooleanField(default=False, verbose_name=''),
        ),
        migrations.AddField(
            model_name='confirmation',
            name='will_show',
            field=models.BooleanField(default=False, verbose_name=''),
        ),
    ]
